### ISSUE TITLE
Opus audio compression patch for PulseAudio

### ISSUE THREAD

**Issue by arbakker** [vatral/pulse-compression-tester#1]
This issue is not directly related to this repo, but this is the most easy way for me to get in touch.

I am interested in trying out this [patch](https://patchwork.freedesktop.org/patch/169038/) (of which I presume you are the author), but the patch on patchwork suffers from wrapped lines  (presumably due to the email client the patch was sent with) and also a number of lines is missing at the end of the patch. I tried to solve these issues by hand , but could not apply the patch cleanly to [tags/v10.0](https://github.com/pulseaudio/pulseaudio/releases/tag/v10.0).

Are you willing to share the original patch with me through Github Gists? And if so, to what commit of the pulseaudio repo should the patch be applied?

**Comment by vatral** [comment]
Hello!

I am traveling right now, but I will get back to you as soon as I get back to my hotel. Meanwhile, we have uploaded the PA code to https://github.com/theqvd/pulseaudio which I think should work for you.

I will bring it up to date with the latest PA development and make a new patch as soon as I get some time for it.

Please report any feedback or suggestions :-)

**Comment by arbakker** [comment]
Awesome, thanks! Do you think the Opus compression is going to land in an official PA release in the near future? That would be pretty neat IMO.

**Comment by vatral** [comment]
I'm not sure. There has been some interest in the functionality for some time. My patch is an update and improvement of a previous one.

But there have been some comments that it might be a bit outside of the scope of the project.

I've tried submitting it upstream but haven't heard back yet. I think I could make the case that it's an useful addition, but whether it goes in or not is not up to me of course.

**Comment by vatral** [comment]
Updated the repository at  https://github.com/theqvd/pulseaudio 

There are two branches:

opus-compression is what we started with. It's the original opus compression patch, updated to apply to the latest code (https://github.com/pulseaudio/pulseaudio master).

opus-extraopts is built on top of that, and adds realtime configurability of pretty much every opus variable. This makes it possible to change the audio quality in real time. This application (pulse-compression-tester) was written to demonstrate that. It's a demo and not a production app, so there might be issues with it, but it should work.

**Comment by arbakker** [comment]
Thanks! 

Do you happen to have some tips on compiling PA from source? I tried the steps outlined [here](https://www.freedesktop.org/wiki/Software/PulseAudio/Documentation/Developer/PulseAudioFromGit/) but the bootstrap script because it cannot find the the configure script:

``
aclocal: couldn't open `configure.in': No such file or directory
autoreconf: aclocal failed with exit status: 2
./bootstrap.sh: line 50: ./configure: No such file or directory`
``
I suppose I first need to generate the configure script, but not sure how...

**Comment by vatral** [comment]
I'm at the moment again without a proper laptop (traveling around until Friday), but typically the problem is the lack of some dependency. Try installing autoconf, automake and libtool.

Another thing to try is to just install the build dependencies through your package manager, eg:

    apt-get build-dep pulseaudio

That should install everything PA needs to compile. You will have to install libopus-devel as well of course (check the output of configure and make sure transcoding appears as enabled)

**Comment by arbakker** [comment]
Thanks for the help! Turned out I had a very old aclocal (1.4) version installed in `/usr/local/bin/` causing the mishap. Now it all builds as advertised. I have made some weird decisions in the past...

**Comment by arbakker** [comment]
I managed to compile and install PA on my desktop and mediaserver. However I am unable to get it working. I am trying to stream audio from my desktop machine to a my mediaserver. The mediaserver has PA installed as system-wide systemd service, since it is partially headless. On the desktop PA does not start up and hangs on trying to connect to the mediaserver. I captured the log files for the desktop and the mediaserver, see the end of this message.  

I setup the configuration like this:

Client: default.pa

`load-module module-tunnel-sink-new sink_name=tunnel server=tcp:192.168.2.5:4713 sink=alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo compression=opus`

Receiver: default.pa

`load-module module-native-protocol-tcp auth-ip-acl=192.168.2.3`

Any idea what could be causing the problem? 

PulseAudio log client (desktop):

```
I: [pulseaudio] sink.c: Created sink 2 "tunnel" with sample spec s16le 2ch 48000Hz and channel map front-left,front-right
I: [pulseaudio] sink.c:     compression.algorithm = "opus"
I: [pulseaudio] sink.c:     compression.bitrate = "64000"
I: [pulseaudio] sink.c:     compression.frame_size = "2880"
I: [pulseaudio] sink.c:     compression.opus.complexity = "10"
I: [pulseaudio] sink.c:     compression.opus.max_bandwidth = "fullband"
I: [pulseaudio] sink.c:     compression.opus.signal = "auto"
I: [pulseaudio] sink.c:     compression.opus.vbr = "0"
I: [pulseaudio] sink.c:     compression.opus.vbr_constraint = "0"
I: [pulseaudio] sink.c:     compression.opus.application = "audio"
I: [pulseaudio] sink.c:     compression.opus.lsb_depth = "24"
I: [pulseaudio] sink.c:     compression.opus.dtx = "0"
I: [pulseaudio] sink.c:     device.class = "sound"
I: [pulseaudio] sink.c:     device.description = "Tunnel to tcp:192.168.2.5:4713/alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"
I: [pulseaudio] sink.c:     device.icon_name = "audio-card"
D: [pulseaudio] module-device-restore.c: Database contains no data for key: source:tunnel.monitor
D: [pulseaudio] module-device-restore.c: Database contains no (or invalid) data for key: source:tunnel.monitor:null
I: [pulseaudio] source.c: Created source 3 "tunnel.monitor" with sample spec s16le 2ch 48000Hz and channel map front-left,front-right
I: [pulseaudio] source.c:     device.description = "Monitor of Tunnel to tcp:192.168.2.5:4713/alsa_output.usb-Burr-Brown_from_TI_USB_Audio_CODEC-00.analog-stereo"
I: [pulseaudio] source.c:     device.class = "monitor"
I: [pulseaudio] source.c:     device.icon_name = "audio-input-microphone"
D: [tunnel-sink] module-tunnel-sink-new.c: Thread starting up
D: [tunnel-sink] conf-parser.c: Parsing configuration file '/etc/pulse/client.conf'
D: [tunnel-sink] conf-parser.c: /etc/pulse/client.conf.d does not exist, ignoring.
D: [tunnel-sink] memblock.c: Using shared memfd memory pool with 1024 slots of size 64,0 KiB each, total size is 64,0 MiB, maximum usable slot size is 65472
D: [tunnel-sink] context.c: Trying to connect to tcp:192.168.2.5:4713...
```


PulseAudio log receiver (mediaserver):

```
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] socket-server.c: TCP connection accepted by tcpwrap.
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] client.c: Created 10 "Native client (TCP/IP client from 192.168.2.3:40232)"
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] protocol-native.c: Client authenticated by IP ACL.
Feb  8 22:15:05  pulseaudio[8289]: W: [pulseaudio] pstream.c: Received SHM frame on a socket where SHM is disabled.
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] client.c: Freed 10 "Native client (TCP/IP client from 192.168.2.3:40232)"
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] protocol-native.c: Connection died.
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] socket-server.c: TCP connection accepted by tcpwrap.
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] client.c: Created 11 "Native client (TCP/IP client from 192.168.2.3:40234)"
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] protocol-native.c: Client authenticated by IP ACL.
Feb  8 22:15:05  pulseaudio[8289]: W: [pulseaudio] pstream.c: Received SHM frame on a socket where SHM is disabled.
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] client.c: Freed 11 "Native client (TCP/IP client from 192.168.2.3:40234)"
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] protocol-native.c: Connection died.
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] socket-server.c: TCP connection accepted by tcpwrap.
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] client.c: Created 12 "Native client (TCP/IP client from 192.168.2.3:40236)"
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] protocol-native.c: Client authenticated by IP ACL.
Feb  8 22:15:05  pulseaudio[8289]: W: [pulseaudio] pstream.c: Received SHM frame on a socket where SHM is disabled.
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] client.c: Freed 12 "Native client (TCP/IP client from 192.168.2.3:40236)"
Feb  8 22:15:05  pulseaudio[8289]: I: [pulseaudio] protocol-native.c: Connection died.
```

**Comment by arbakker** [comment]
Closing, since I have no need to stream audio through PA anymore.
